services:
  frontend:
    container_name: angular-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    restart: always